<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AuthService.Application\AuthService.Application.csproj" />
    <ProjectReference Include="..\AuthService.Domain\AuthService.Domain.csproj" />
    <ProjectReference Include="..\AuthService.Infrastructure\AuthService.Infrastructure.csproj" />
    <ProjectReference Include="..\AuthService.ReadModel\AuthService.ReadModel.csproj" />
    <ProjectReference Include="..\AuthService.Contracts\AuthService.Contracts.csproj" />
    <ProjectReference Include="..\AuthService.ServiceDefaults\AuthService.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
