// <auto-generated />
using System.Text;
using AuthService.Application.Features.Auth;
using AuthService.Contracts;
using AuthService.Domain.Common;
using AuthService.Domain.Users;
using AuthService.Infrastructure.Setup;
using AuthService.ReadModel.Queries;
using FluentValidation;
using Mapster;
using MediatR;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Serilog
builder.Host.UseSerilog((ctx, lc) => lc
    .ReadFrom.Configuration(ctx.Configuration)
    .Enrich.FromLogContext()
    .Enrich.WithEnvironmentName()
    .WriteTo.Console());

// Aspire Service Defaults
builder.Services.AddServiceDefaults();

// Infrastructure (DbContexts + Identity + Repos + TokenService)
builder.Services.AddInfrastructure(builder.Configuration);

// MediatR, Mapster, FluentValidation
builder.Services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblyContaining<RegisterHandler>());
builder.Services.AddValidatorsFromAssemblyContaining<RegisterHandler>();
builder.Services.AddMapster();

// Authentication - JWT
builder.Services.AddAuthentication(o =>
{
    o.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(o =>
{
    o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"],
        ValidAudience = builder.Configuration["Jwt:Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:SigningKey"]!))
    };
})
// External providers (Google/Microsoft) - for demo/testing
.AddGoogle("Google", o =>
{
    o.ClientId = builder.Configuration["Authentication:Google:ClientId"]!;
    o.ClientSecret = builder.Configuration["Authentication:Google:ClientSecret"]!;
})
.AddMicrosoftAccount("Microsoft", o =>
{
    o.ClientId = builder.Configuration["Authentication:Microsoft:ClientId"]!;
    o.ClientSecret = builder.Configuration["Authentication:Microsoft:ClientSecret"]!;
});

builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new AuthorizationPolicyBuilder()
        .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
        .RequireAuthenticatedUser()
        .Build();
    options.AddPolicy("RequireAdmin", p => p.RequireRole("Admin"));
});

// HttpClientFactory
builder.Services.AddHttpClient();

// HealthChecks
builder.Services.AddHealthChecks()
    .AddSqlServer(builder.Configuration.GetConnectionString("SqlServer")!)
    .AddNpgSql(builder.Configuration.GetConnectionString("Postgres")!);

// CORS (example)
builder.Services.AddCors(p => p.AddDefaultPolicy(b => b.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin()));

var app = builder.Build();

app.UseSerilogRequestLogging();
app.UseCors();
app.UseAuthentication();
app.UseAuthorization();

// Minimal API endpoints under feature folders

var api = app.MapGroup("/api");
api.MapGet("/health", () => Results.Ok(new { status = "ok" })).AllowAnonymous();

// Register
api.MapPost("/auth/register", async (AuthDtos.RegisterRequest req, ISender sender, IValidator<RegisterCommand> validator) =>
{
    var cmd = new RegisterCommand(req.Email, req.Password, req.FirstName, req.LastName);
    var v = await validator.ValidateAsync(cmd);
    if (!v.IsValid) return Results.BadRequest(v.Errors.Select(e => new { e.PropertyName, e.ErrorMessage }));
    var res = await sender.Send(cmd);
    return res.IsSuccess ? Results.Created($"/api/users/{res.Value}", new { id = res.Value }) : Results.BadRequest(res.Error);
}).AllowAnonymous();

// Login
api.MapPost("/auth/login", async (AuthDtos.LoginRequest req, ISender sender, IValidator<LoginCommand> validator) =>
{
    var cmd = new LoginCommand(req.Email, req.Password, req.TwoFactorCode);
    var v = await validator.ValidateAsync(cmd);
    if (!v.IsValid) return Results.BadRequest(v.Errors.Select(e => new { e.PropertyName, e.ErrorMessage }));
    var res = await sender.Send(cmd);
    return res.IsSuccess ? Results.Ok(res.Value) : Results.BadRequest(res.Error);
}).AllowAnonymous();

// Refresh
api.MapPost("/auth/refresh", async (AuthDtos.RefreshTokenRequest req, ISender sender, IHttpContextAccessor accessor) =>
{
    var userId = accessor.HttpContext!.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (Guid.TryParse(userId, out var uid) is false) return Results.Unauthorized();
    var res = await sender.Send(new RefreshTokenCommand(uid, req.RefreshToken));
    return res.IsSuccess ? Results.Ok(res.Value) : Results.BadRequest(res.Error);
});

// Profile (Queries via PostgreSQL ReadDbContext)
api.MapGet("/auth/profile", async (ISender sender, ClaimsPrincipal user) =>
{
    var idStr = user.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (!Guid.TryParse(idStr, out var uid)) return Results.Unauthorized();
    var res = await sender.Send(new GetProfile(uid));
    return res.IsSuccess ? Results.Ok(res.Value) : Results.NotFound(res.Error);
});

// Address CRUD (Command side)
api.MapPost("/auth/addresses", async (AuthDtos.AddressRequest req, AuthService.Application.Abstractions.IUserRepository repo, ClaimsPrincipal user) =>
{
    var idStr = user.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (!Guid.TryParse(idStr, out var uid)) return Results.Unauthorized();
    var addr = req.Adapt<AuthService.Domain.Users.Address>();
    var res = await repo.AddAddressAsync(uid, addr, default);
    return res.IsSuccess ? Results.Created($"/api/auth/addresses/{addr.Id}", addr) : Results.BadRequest(res.Error);
});

api.MapGet("/auth/addresses", async (AuthService.Application.Abstractions.IUserRepository repo, ClaimsPrincipal user) =>
{
    var idStr = user.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (!Guid.TryParse(idStr, out var uid)) return Results.Unauthorized();
    var res = await repo.GetAddressesAsync(uid, default);
    return res.IsSuccess ? Results.Ok(res.Value) : Results.BadRequest(res.Error);
});

// 2FA Endpoints
api.MapPost("/auth/2fa/enable", async (UserManager<AppUser> um, ClaimsPrincipal user) =>
{
    var idStr = user.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (!Guid.TryParse(idStr, out var uid)) return Results.Unauthorized();
    var u = await um.FindByIdAsync(uid.ToString());
    if (u is null) return Results.Unauthorized();
    await um.SetTwoFactorEnabledAsync(u, true);
    var key = await um.GetAuthenticatorKeyAsync(u) ?? (await um.ResetAuthenticatorKeyAsync(u), await um.GetAuthenticatorKeyAsync(u)).Item2;
    return Results.Ok(new { sharedKey = key });
});

api.MapPost("/auth/2fa/verify/{code}", async (string code, UserManager<AppUser> um, ClaimsPrincipal user) =>
{
    var idStr = user.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (!Guid.TryParse(idStr, out var uid)) return Results.Unauthorized();
    var u = await um.FindByIdAsync(uid.ToString());
    if (u is null) return Results.Unauthorized();
    var valid = await um.VerifyTwoFactorTokenAsync(u, TokenOptions.DefaultAuthenticatorProvider, code);
    return valid ? Results.Ok() : Results.BadRequest(new { error = "Invalid code" });
});

// External auth endpoints (demo - for real apps you'd manage cookie scheme + callback)
api.MapPost("/auth/external", (AuthDtos.ExternalLoginRequest req) =>
{
    // In a production API you'd validate the IdToken with the provider and map to a user.
    // This stub is here to keep the sample compile-time complete.
    return Results.Ok(new { provider = req.Provider, ok = true });
}).AllowAnonymous();

// Swagger (minimal inline)
app.MapGet("/", () => Results.Redirect("/api/health"));

// Migrate + seed
await Seed.ApplyAsync(app.Services);

app.Run();

public partial class Program { }
